# la verion del api que  vamos a usar en kubernetes
apiVersion : v1
# tipo de elemento de despliegue en kubernetes
kind : Pod
metadata :
  name: mi-app
spec:
  containers:
    - name: mi-app
      #docker hub y me voy a traer mi aplicacion
      image: dhaker/miapp
      resources:
        limits: 
          memory: 512Mi
          cpu: 1
