apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: ClusterIP
  selector:
    app: mi-mysql # busca el deployment que tenga esa label
  ports: # puertos que va a escuchar
  - name: mysql
    port: 3306
    targetPort: 3306


