apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-mysql
  labels:
    app: mi-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mi-mysql
  template:
    metadata:
      labels:
        app: mi-mysql
    spec:
      containers:
      - name: mi-mysql
        image: mysql:5.7
        resources:
            limits: 
              memory: 512Mi
              cpu: "1"
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
        - name: MYSQL_DATABASE
          value: "wordpress"
        - name: MYSQL_USER
          value: "wordpress"
        - name: MYSQL_PASSWORD
          value: "wordpress"