# la verion del api que  vamos a usar en kubernetes
apiVersion : v1
# tipo de elemento de despliegue en kubernetes
kind : Service
metadata :
  name: miservicio-tomcat
spec:
  type: LoadBalancer
  ports:
    #este es el puerto de destino nginx corre en el 80
    - targetPort: 8080
      # puerto del servicio
      port: 8080
      # puerto externo el puerto del nodo que se publica
      nodePort: 30004 
  selector: 
      app: web